# Generated by Django 4.2.30 on 2026-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_companyinfo_dictionaryterm_employee_news_promocode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
